require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


# target 'MapApp' do
#   config = use_native_modules!

#   use_react_native!(:path => config["reactNativePath"])

#   pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

#   # target 'MapAppTests' do
#   #   inherit! :complete
#   #   # Pods for testing
#   # end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   # use_flipper!
#   # post_install do |installer|
#   #   flipper_post_install(installer)
#   # end
# end

target 'MapApp-tvOS' do
  platform :tvos, '11.0'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
  # pod 'react-native-mapbox-gl/DynamicLibrary', :path => '../node_modules/@react-native-mapbox-gl/maps'
  # pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
  # pod 'NoUseFrameworks-MapboxMobileEvents',  :podspec => '../node_modules/@react-native-mapbox-gl/maps/ios/NoUseFrameworks-MapboxMobileEvents/NoUseFrameworks-MapboxMobileEvents.podspec.json'

  # use_frameworks!


  # Pods for MapApp-tvOS

  # target 'MapApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
end
